# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


use_frameworks!

target 'AllStars' do

pod 'Alamofire', '~> 3.4'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Firebase'
pod 'Firebase/Messaging'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

end